/* ProMedia Jobs — дані каталогу.
   Базові вакансії з джерелами зберігаються в цьому файлі. Тимчасові вакансії
   роботодавців із тестового кабінету живуть у localStorage браузера. */

const FORMATS = [
  { id: "office", label: "Офіс" },
  { id: "remote", label: "Дистанційно" },
  { id: "hybrid", label: "Гібридно" },
];

const EMPLOYMENT_TYPES = [
  { id: "full", label: "Повна зайнятість" },
  { id: "part", label: "Часткова зайнятість" },
  { id: "project", label: "Проєктна робота" },
  { id: "freelance", label: "Фриланс" },
  { id: "temporary", label: "Тимчасова" },
  { id: "internship", label: "Стажування" },
  { id: "volunteering", label: "Волонтерство" },
];

const PERKS = [
  { id: "insurance", label: "Медстрахування" },
  { id: "food", label: "Харчування" },
  { id: "english", label: "Англійська" },
  { id: "psychologist", label: "Психолог" },
];

const EMPLOYMENT_ARRANGEMENTS = [
  { id: "labor", label: "Трудова" },
  { id: "civil", label: "Цивільно-правова угода" },
  { id: "sole-prop", label: "ФОП" },
  { id: "other", label: "Інший формат" },
];

const REGIONS = [
  "Вся Україна", "м. Київ", "Вінницька область", "Волинська область", "Дніпропетровська область",
  "Донецька область", "Житомирська область", "Закарпатська область", "Запорізька область",
  "Івано-Франківська область", "Київська область", "Кіровоградська область", "Луганська область",
  "Львівська область", "Миколаївська область", "Одеська область", "Полтавська область",
  "Рівненська область", "Сумська область", "Тернопільська область", "Харківська область",
  "Херсонська область", "Хмельницька область", "Черкаська область", "Чернівецька область",
  "Чернігівська область",
];

function labelOf(list, id) {
  const it = list.find((x) => x.id === id);
  return it ? it.label : id;
}

const COMPANIES = [
  { id: "suspilne", name: "Суспільне мовлення", letter: "С", color: "#0d0c5c", city: "Київ", industry: "Телебачення / Радіо",
    desc: "Національна суспільна медіаплатформа: телебачення, радіо, онлайн-редакція.", site: "suspilne.media" },
  { id: "ukrainska-pravda", name: "Українська правда", letter: "П", color: "#201e78", city: "Київ", industry: "Онлайн-медіа",
    desc: "Одне з найбільших онлайн-видань України.", site: "pravda.com.ua" },
  { id: "the-village", name: "The Village Україна", letter: "V", color: "#d98a17", city: "Київ", industry: "Медіа / Лайфстайл",
    desc: "Медіа про місто, культуру та людей.", site: "village.com.ua" },
  { id: "promedia-agency", name: "PR-агенція «Резонанс»", letter: "Р", color: "#1c9a56", city: "Львів", industry: "PR / Комунікації",
    desc: "Комунікаційна агенція повного циклу для бізнесу та НГО.", site: "rezonans-agency.ua" },
  { id: "adhouse", name: "AdHouse Digital", letter: "A", color: "#c9932c", city: "Дніпро", industry: "Реклама / Маркетинг",
    desc: "Перформанс-маркетинг та діджитал-реклама для e-commerce.", site: "adhouse.agency" },
  { id: "ngo-medialab", name: "МедіаЛаб (ГО)", letter: "М", color: "#8b8fa0", city: "Харків", industry: "Медіаграмотність / Освіта",
    desc: "Громадська організація: тренінги з медіаграмотності та фактчекінгу.", site: "medialab.org.ua" },
  { id: "ti-ukraine", name: "Transparency International Ukraine", letter: "T", color: "#0f4c81", city: "Київ", industry: "Громадська організація / Антикорупція",
    desc: "Акредитований представник глобального руху Transparency International: з 2012 року допомагає Україні ставати сильнішою, розробляючи й впроваджуючи зміни для зниження рівня корупції. Допомогла створити Prozorro, Prozorro.Продажі, eHealth та Prozvit, впровадила Рейтинги прозорості та підзвітності міст, розбудувала спільноту DOZORRO.", site: "ti-ukraine.org" },
];

function companyOf(id) { return COMPANIES.find((c) => c.id === id); }

/* Старі тестові вакансії залишені в коді як архів, але не показуються в
   публічному каталозі: сайт має показувати лише записи із зарплатою та
   зрозумілими умовами оформлення. */
const VACANCIES = [
  {
    id: "v1", title: "SMM-менеджер(ка)", companyId: "ti-ukraine",
    region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: false,
    employmentType: "full", experienceYears: 2,
    responsibilities: [
      "Реалізація та розвиток стратегії просування організації у соціальних мережах (пріоритетні: Facebook, Telegram, Instagram)",
      "Формування контент-плану під визначені KPI, пошук нових форматів і трендів",
      "Генерування ідей, написання сценаріїв, самостійна зйомка та монтаж caption-відео й Reels",
      "Створення текстів та візуалів для публікацій, постановка ТЗ дизайнерам за потреби",
      "Планування, запуск і оптимізація рекламних кампаній, управління бюджетом платного просування",
      "Ведення комунікації з підписниками: відповіді на коментарі та повідомлення в директ",
      "Налагодження партнерства й колаборації у соціальних мережах із залученням комунікаційної команди",
      "Аналіз ефективності роботи (Meta Business Suite, TGStat, GA4), підготовка щомісячних звітів та висновків для команди",
    ],
    mustHave: [
      "Понад 2 роки досвіду у SMM, бажано в медіа чи громадському секторі",
      "Розуміння різниці між контекстною та таргетованою рекламою, кейси успішних рекламних кампаній у соцмережах",
      "Впевнене володіння аналітикою, вміння робити пропозиції, підкріплені цифрами",
      "Вміння пояснювати складні речі простою мовою та створювати контент, що викликає емоції й залучає",
      "Вільна українська; англійська — не нижче B1",
    ],
    niceToHave: ["Впевнене володіння графічними редакторами та програмами для відеомонтажу"],
    education: "Не вказано",
    skills: ["SMM", "Контент-план", "Копірайтинг", "Таргетована реклама", "Відеомонтаж"],
    tools: ["Meta Business Suite", "TGStat", "GA4"],
    languages: ["Українська — вільно", "Англійська — не нижче B1"],
    salaryMin: 0, salaryMax: 0, currency: "UAH",
    perks: [], perksOther: [], employmentArrangement: "",
    benefits: [
      "Робота з суспільно-важливим інформаційним продуктом",
      "Open-minded команда, яка щиро вітає пропозиції щодо змін",
      "Конкурентна винагорода залежно від досвіду та результатів співбесіди",
      "Гнучкий гібридний формат роботи (online + offline)",
      "Офіс у центрі Києва (метро «Золоті Ворота»)",
      "Компенсація навчання для професійного зростання",
      "24 календарні дні відпустки на рік",
    ],
    contactEmail: "hr-tiu@ti-ukraine.org",
    publishedAt: "2026-07-27", expiresAt: "2026-07-31",
    source: "direct", sourceUrl: "", direct: true,
    moderationStatus: "approved", active: false,
  },
  {
    id: "v2", title: "PR-менеджер(ка)", companyId: null, companyName: "NDA",
    region: "Миколаївська область", country: "Україна", format: "hybrid", remoteOk: false,
    employmentType: "full", experienceYears: 0,
    responsibilities: [
      "Антикризова комунікація: розробка та реалізація стратегій реагування на кризові ситуації, робота з репутаційними ризиками, мінімізація негативу в інфопросторі",
      "Робота зі ЗМІ: взаємодія з регіональними та національними медіа, написання прес-релізів, коментарів, організація інтерв'ю та брифінгів",
      "Створення контенту: підготовка офіційних заяв, текстів для медіа, блогу чи соцмереж щодо критичних та важливих подій",
      "Моніторинг та аналітика: щоденне відстеження згадок про компанію в інформаційному полі (Media Monitoring), аналіз медіаполя",
    ],
    mustHave: [], niceToHave: [],
    education: "Не вказано",
    skills: ["PR", "Антикризові комунікації", "Робота зі ЗМІ", "Медіамоніторинг"],
    tools: [], languages: ["Українська — рідна"],
    salaryMin: 0, salaryMax: 0, currency: "UAH",
    perks: [], perksOther: [], employmentArrangement: "labor",
    benefits: [
      "Офіс — у разі кризової ситуації, решта часу — віддалена взаємодія з партнерськими регіонами",
      "Офіційне оформлення (деталі — на співбесіді)",
    ],
    contactEmail: "missionofficialca@gmail.com",
    publishedAt: "2026-07-27", expiresAt: "2026-08-26",
    source: "direct", sourceUrl: "", direct: true,
    moderationStatus: "approved", active: false,
  },
  {
    id: "v3", title: "SMM-менеджер(ка)", companyId: null, companyName: "NDA",
    region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: false,
    employmentType: "full", experienceYears: 0,
    responsibilities: [
      "Імплементація стратегії та планування: розробка контент-плану, вибір платформ (Instagram, TikTok, Facebook, LinkedIn тощо) під задану цільову аудиторію",
      "Створення контенту: написання текстів, зйомка та монтаж відео (Reels, TikTok), створення фото та дизайну (сторіс, пости)",
      "Ведення та оформлення сторінок: регулярна публікація постів, оформлення актуальних (Highlights), підтримка візуального стилю бренду",
      "Комунікація з аудиторією: відповіді на коментарі та повідомлення в Direct, робота із запереченнями, підвищення залученості (Engagement Rate)",
      "Таргетована реклама: налаштування та запуск платних рекламних кампаній (або робота в парі з таргетологом)",
      "Колаборації та інфлюенс-маркетинг: пошук блогерів для партнерства",
      "Аналітика та звітність: відстеження показників охоплень, приросту аудиторії, конверсій та ефективності контенту",
    ],
    mustHave: [], niceToHave: [],
    education: "Не вказано",
    skills: ["SMM", "Контент-план", "Таргетована реклама", "Відеомонтаж", "Аналітика"],
    tools: ["Instagram", "TikTok", "Facebook", "LinkedIn"], languages: ["Українська — рідна"],
    salaryMin: 0, salaryMax: 0, currency: "UAH",
    perks: [], perksOther: [], employmentArrangement: "labor",
    benefits: [
      "Офіційне оформлення",
      "Віддалений формат роботи з обов'язковими виїздами в офіс та на заходи компанії",
    ],
    contactEmail: "missionofficialca@gmail.com",
    publishedAt: "2026-07-27", expiresAt: "2026-08-26",
    source: "direct", sourceUrl: "", direct: true,
    moderationStatus: "approved", active: false,
  },
  {
    id: "v4", title: "PR-менеджер(ка)", companyId: null, companyName: "NDA",
    region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: false,
    employmentType: "full", experienceYears: 0,
    responsibilities: [
      "Імплементація існуючої стратегії, адаптація під аудиторію",
      "Робота зі ЗМІ: написання прес-релізів, статей, коментарів, організація інтерв'ю та пресконференцій, формування бази журналістів",
      "Підвищення впізнаваності, формування позитивного іміджу компанії та її перших осіб",
      "Пошук партнерів, блогерів для колаборацій та нативних інтеграцій",
      "Створення контенту: підготовка текстів для соцмереж, сайту, блогу, спецпроєктів чи презентацій",
    ],
    mustHave: [], niceToHave: ["Англійська мова"],
    education: "Не вказано",
    skills: ["PR", "Робота зі ЗМІ", "Копірайтинг", "Партнерства"],
    tools: [], languages: ["Українська — рідна"],
    salaryMin: 0, salaryMax: 0, currency: "UAH",
    perks: [], perksOther: [], employmentArrangement: "labor",
    benefits: [
      "Офіційне оформлення",
      "Віддалений формат роботи з можливими виїздами в офіс у Києві",
    ],
    contactEmail: "missionofficialca@gmail.com",
    publishedAt: "2026-07-27", expiresAt: "2026-08-26",
    source: "direct", sourceUrl: "", direct: true,
    moderationStatus: "approved", active: false,
  },
  {
    id: "work-7998066", title: "Бренд-менеджер, менеджерка інформаційно-новинного напряму",
    companyId: "suspilne", region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: false,
    employmentType: "full", experienceYears: 2,
    responsibilities: [
      "Розвивати бренди інформаційно-новинного напряму Суспільного та окремі медійні проєкти",
      "Планувати бренд-комунікації, працювати з аудиторіями, кампаніями та аналітикою",
      "Координувати взаємодію між редакційними, маркетинговими та комунікаційними командами",
    ],
    mustHave: [
      "Досвід бренд-менеджменту або маркетингових комунікацій від 2 років",
      "Розуміння медійного ринку та інформаційних продуктів",
      "Українська вільно, англійська не нижче B1",
    ],
    niceToHave: ["Досвід роботи з медійними брендами або суспільно важливими проєктами"],
    education: "Вища освіта",
    skills: ["Бренд-менеджмент", "Комунікації", "Медіа", "Аналітика", "Кампанії"],
    tools: ["PowerPoint", "Excel"],
    languages: ["Українська — вільно", "Англійська — від B1"],
    salaryMin: 35000, salaryMax: 35000, currency: "UAH",
    perks: [], perksOther: ["безпечне робоче середовище", "підтримка професійного розвитку"],
    employmentArrangement: "labor",
    benefits: [
      "Гібридний графік роботи",
      "Гарантоване офіційне працевлаштування",
      "Робота з національними суспільними медійними брендами",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/7998066/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/7998066/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-8352552", title: "Редактор, редакторка угорської мовної редакції",
    companyId: "suspilne", region: "Закарпатська область", country: "Україна", format: "hybrid", remoteOk: false,
    employmentType: "full", experienceYears: 0,
    responsibilities: [
      "Готувати мультимедійні журналістські матеріали угорською мовою",
      "Працювати з відеоконтентом для YouTube та редакційними форматами Суспільного",
      "Дотримуватися редакційних стандартів, фактчекінгу та драматургії журналістського матеріалу",
    ],
    mustHave: [
      "Вільна українська та угорська мови",
      "Вища освіта",
      "Розуміння журналістських стандартів і структури мультимедійного матеріалу",
    ],
    niceToHave: ["Досвід роботи з відео або YouTube-форматами"],
    education: "Вища освіта",
    skills: ["Редагування", "Журналістика", "YouTube", "Мультимедіа", "Фактчекінг"],
    tools: ["YouTube"],
    languages: ["Українська — вільно", "Угорська — вільно"],
    salaryMin: 21960, salaryMax: 21960, currency: "UAH",
    perks: [], perksOther: ["безпечне робоче середовище", "підтримка колективної співпраці"],
    employmentArrangement: "labor",
    benefits: [
      "Гібридний графік роботи",
      "Гарантоване офіційне працевлаштування",
      "Робота над суспільно важливим контентом",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/8352552/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/8352552/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-8081928", title: "Редактор юридичного видання",
    companyId: null, companyName: "Перша Правова Медіагрупа",
    region: "м. Київ", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Редагувати матеріали юридичного видання та готувати тексти до публікації",
      "Працювати із CMS, SEO-завданнями та структурою сторінок",
      "Підтримувати точність, грамотність і зрозумілість редакційних матеріалів",
    ],
    mustHave: [
      "Досвід редагування від 1 року",
      "Грамотна усна та письмова українська",
      "Уважність до фактів, стилю та юридичної тематики",
    ],
    niceToHave: ["Досвід роботи з WordPress, Tilda або SEO"],
    education: "Не вказано",
    skills: ["Редагування", "Журналістика", "SEO", "CMS", "Юридична тематика"],
    tools: ["WordPress", "Tilda"],
    languages: ["Українська — вільно"],
    salaryMin: 35000, salaryMax: 35000, currency: "UAH",
    perks: [], perksOther: ["редакційна робота у профільному медіа"],
    employmentArrangement: "other",
    benefits: [
      "Повна зайнятість",
      "Офісна робота в Києві",
      "Джерело вказує зарплату та повний формат зайнятості, деталі оформлення слід уточнити в роботодавця",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/8081928/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/8081928/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: false,
  },
  {
    id: "work-8329380", title: "SMM Manager (MilTech)",
    companyId: null, companyName: "Д.Ж.Е.Т.",
    region: "м. Київ", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 2,
    responsibilities: [
      "Розвивати соціальні мережі miltech-компанії та адаптувати складні теми для аудиторії",
      "Створювати контент-плани, пости, короткі відео та візуальні матеріали",
      "Аналізувати ефективність контенту й координувати роботу з командою",
    ],
    mustHave: [
      "Досвід SMM від 2 років",
      "Вміння писати просто про технологічні теми",
      "Навички роботи з аналітикою та візуальним контентом",
    ],
    niceToHave: ["Інтерес до defense tech або технологічних продуктів"],
    education: "Не вказано",
    skills: ["SMM", "MilTech", "Контент-план", "Копірайтинг", "Аналітика"],
    tools: ["Instagram", "Facebook", "TikTok"],
    languages: ["Українська — вільно"],
    salaryMin: 60000, salaryMax: 80000, currency: "UAH",
    perks: ["insurance"], perksOther: ["бронювання відповідно до чинного законодавства"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування",
      "Медичне страхування після випробувального терміну",
      "Офіс у Києві біля Контрактової площі",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/8329380/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/8329380/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-8352924", title: "SMM-менеджер, графічний дизайнер",
    companyId: null, companyName: "Брана, ТОВ",
    region: "Київська область", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Вести соціальні мережі та готувати графічні матеріали для комунікацій компанії",
      "Працювати із зовнішньою рекламою, візуалами та регулярним контентом",
      "Підтримувати єдиний стиль бренду в цифрових і друкованих матеріалах",
    ],
    mustHave: [
      "Досвід SMM або графічного дизайну від 1 року",
      "Уважність до деталей і вміння працювати з дедлайнами",
      "Навички створення візуального контенту",
    ],
    niceToHave: ["Готовність поєднувати SMM і дизайн-задачі"],
    education: "Не вказано",
    skills: ["SMM", "Графічний дизайн", "Контент", "Зовнішня реклама"],
    tools: ["Canva", "Adobe"],
    languages: ["Українська — вільно"],
    salaryMin: 40000, salaryMax: 40000, currency: "UAH",
    perks: [], perksOther: ["комфортні та безпечні умови праці"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування",
      "Конкурентна зарплата за результатами співбесіди",
      "Цікаві проєкти та можливість професійного розвитку",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/8352924/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/8352924/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-8283930", title: "Influencer Marketing Manager",
    companyId: null, companyName: "bodo",
    region: "м. Київ", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 2,
    responsibilities: [
      "Організовувати інтеграції з блогерами та інфлюенсерами в Instagram і YouTube",
      "Працювати з UGC-контентом, брифами, бюджетом і результатами кампаній",
      "Вести базу креаторів, домовленостей, умов співпраці та висновків",
    ],
    mustHave: [
      "Досвід influencer marketing від 2 років",
      "Вміння домовлятися про умови інтеграцій і оцінювати ефективність контенту",
      "Досвід роботи з Instagram, YouTube та UGC-форматами",
    ],
    niceToHave: ["Досвід PR-активностей бренду"],
    education: "Вища освіта",
    skills: ["Influencer marketing", "UGC", "PR", "YouTube", "Instagram"],
    tools: ["Instagram", "YouTube"],
    languages: ["Українська — вільно"],
    salaryMin: 70000, salaryMax: 85000, currency: "UAH",
    perks: [], perksOther: ["квартальний бонус", "sign up bonus після першого місяця"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування з першого робочого дня",
      "Ставка та бонусна частина за результатами роботи",
      "Робота з блогерами, креаторами та PR-активностями бренду",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/8283930/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/8283930/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-8294148", title: "Молодший контент-менеджер",
    companyId: null, companyName: "Zemits Ukraine",
    region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Оновлювати контент сайту, публікувати статті та налаштовувати промоблоки",
      "Працювати з продуктовими матеріалами, текстами й технічними правками",
      "Підтримувати якість контенту на українському та міжнародному ринках",
    ],
    mustHave: [
      "Досвід контент-менеджменту від 1 року",
      "Уважність до деталей і готовність працювати з технічними налаштуваннями",
      "Вища освіта або релевантний практичний досвід",
    ],
    niceToHave: ["Досвід роботи з e-commerce або beauty/wellness-продуктами"],
    education: "Вища освіта",
    skills: ["Контент-менеджмент", "CMS", "SEO", "Редагування", "Публікації"],
    tools: ["CMS"],
    languages: ["Українська — вільно"],
    salaryMin: 27000, salaryMax: 33000, currency: "UAH",
    perks: [], perksOther: ["гібридний графік"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування",
      "Конкурентна зарплата",
      "Гібридний графік роботи",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/8294148/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/8294148/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-6681709", title: "Partnership Manager (партнерство, залучення фінансування)",
    companyId: null, companyName: "Мирне Небо Харкова, БФ, БО",
    region: "Харківська область", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Будувати партнерства та залучати фінансування для благодійної організації",
      "Працювати з донорами, партнерами, презентаціями та комунікаційними матеріалами",
      "Підтримувати системну взаємодію з командою і зовнішніми стейкхолдерами",
    ],
    mustHave: [
      "Досвід партнерств, фандрейзингу, комунікацій або продажів",
      "Сильні навички письмової та усної комунікації",
      "Готовність працювати з соціально важливою гуманітарною тематикою",
    ],
    niceToHave: ["Досвід роботи в громадському або благодійному секторі"],
    education: "Не вказано",
    skills: ["Партнерства", "Фандрейзинг", "Комунікації", "Презентації"],
    tools: ["Google Workspace", "CRM"],
    languages: ["Українська — вільно"],
    salaryMin: 60000, salaryMax: 80000, currency: "UAH",
    perks: [], perksOther: ["підтримка навчання та розвитку"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне оформлення",
      "П'ятиденний робочий тиждень 9:00-18:00",
      "Сильна команда, де цінується ініціатива",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/6681709/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/6681709/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-8168721", title: "Менеджер з корпоративної культури та внутрішніх комунікацій",
    companyId: null, companyName: "СмартХоум Технолоджіс, ТОВ",
    region: "Івано-Франківська область", country: "Україна", format: "hybrid", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Розвивати внутрішні комунікації та корпоративну культуру компанії",
      "Організовувати події, зустрічі, внутрішні повідомлення та командні активності",
      "Підтримувати регулярну комунікацію з працівниками і керівниками команд",
    ],
    mustHave: [
      "Досвід внутрішніх комунікацій або HR-комунікацій від 1 року",
      "Навички організації заходів і роботи з людьми",
      "Впевнена грамотна українська",
    ],
    niceToHave: ["Досвід проведення індивідуальних зустрічей із працівниками"],
    education: "Не вказано",
    skills: ["Внутрішні комунікації", "Корпоративна культура", "HR-комунікації", "Події"],
    tools: ["MS Office", "Google Workspace"],
    languages: ["Українська — вільно"],
    salaryMin: 28000, salaryMax: 30000, currency: "UAH",
    perks: [], perksOther: ["гнучкий вибір робочого графіка"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування",
      "Гібридний формат роботи",
      "Комфортні умови праці",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/8168721/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/8168721/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-6896056", title: "Графічний дизайнер, фахівець з комунікацій",
    companyId: null, companyName: "Центр рекрутингу Військово-Морських Сил ЗСУ",
    region: "Вся Україна", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 2,
    responsibilities: [
      "Створювати дизайн і візуальні концепції для друкованих комунікаційних матеріалів",
      "Допомагати з оформленням агітаційних, інформаційних і брендованих матеріалів",
      "Працювати у військовому комунікаційному середовищі з дотриманням дедлайнів",
    ],
    mustHave: [
      "Досвід графічного дизайну або комунікацій від 2 років",
      "Готовність до служби за контрактом",
      "Навички роботи з візуальними матеріалами",
    ],
    niceToHave: ["Досвід створення друкованої продукції"],
    education: "Не вказано",
    skills: ["Графічний дизайн", "Комунікації", "Друковані матеріали", "Візуальна айдентика"],
    tools: ["Adobe", "Canva"],
    languages: ["Українська — вільно"],
    salaryMin: 22000, salaryMax: 22000, currency: "UAH",
    perks: [], perksOther: ["служба за контрактом"],
    employmentArrangement: "other",
    benefits: [
      "Вакансія для кандидата, готового підписати контракт",
      "Повна зайнятість",
      "Робота з комунікаціями Військово-Морських Сил",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/6896056/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/6896056/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-8149725", title: "SMM-менеджер",
    companyId: null, companyName: "Військова частина 9960 ДПСУ",
    region: "Хмельницька область", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Вести й розвивати офіційні сторінки військової частини у соціальних мережах",
      "Створювати інформативний і мотивуючий контент про роботу прикордонників",
      "Працювати з фото, відео, текстами та регулярною публікацією матеріалів",
    ],
    mustHave: [
      "Досвід SMM від 1 року",
      "Вміння створювати якісний текстовий і візуальний контент",
      "Готовність працювати з оборонною тематикою",
    ],
    niceToHave: ["Досвід комунікацій у державному або громадському секторі"],
    education: "Не вказано",
    skills: ["SMM", "Контент", "Соцмережі", "Відео", "Фото"],
    tools: ["Facebook", "Instagram", "TikTok"],
    languages: ["Українська — вільно"],
    salaryMin: 22000, salaryMax: 60000, currency: "UAH",
    perks: [], perksOther: ["повний соціальний пакет", "підтримка навчання"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування у стабільній структурі",
      "Повний соціальний пакет",
      "Можливість професійного розвитку",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/8149725/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/8149725/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-7944096", title: "Копірайтер",
    companyId: null, companyName: "Любарт, 20 бригада оперативного призначення НГУ",
    region: "Вся Україна", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Писати рекламні, інформаційні та службові тексти для комунікаційних задач бригади",
      "Працювати із різними стилями: офіційним, нейтральним і розмовним",
      "Адаптувати тексти під аудиторії, канали й конкретні завдання",
    ],
    mustHave: [
      "Досвід копірайтингу від 1 року",
      "Грамотна письмова українська та розуміння стилістики",
      "Готовність до мобілізації або укладання контракту",
    ],
    niceToHave: ["Знання англійської та базове розуміння локалізації"],
    education: "Не вказано",
    skills: ["Копірайтинг", "Рекламні тексти", "Редагування", "Локалізація"],
    tools: [],
    languages: ["Українська — вільно", "Англійська — бажано"],
    salaryMin: 25000, salaryMax: 125000, currency: "UAH",
    perks: [], perksOther: ["контракт або мобілізація до кінця воєнного стану"],
    employmentArrangement: "other",
    benefits: [
      "Сума залежить від завдання та місця служби",
      "Повна зайнятість",
      "Служба за контрактом або мобілізацією",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/7944096/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/7944096/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-7860579", title: "Фотограф, відеограф у ЗСУ",
    companyId: null, companyName: "129 ОВМБр",
    region: "Вся Україна", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Знімати фото й відео, готувати матеріали до публікації та підтримувати комунікації бригади",
      "Працювати із соцмережами, оформленням постів і єдиним стилем подачі",
      "Передавати матеріали оперативно та взаємодіяти з підрозділами",
    ],
    mustHave: [
      "Досвід фото- або відеозйомки від 1 року",
      "Навички монтажу та обробки фото",
      "Готовність до військової служби за контрактом або мобілізацією",
    ],
    niceToHave: ["Досвід роботи з редакційними або документальними матеріалами"],
    education: "Не вказано",
    skills: ["Фотографія", "Відеозйомка", "Відеомонтаж", "Соцмережі"],
    tools: ["Adobe Photoshop", "Adobe Lightroom", "Adobe Premiere Pro"],
    languages: ["Українська — вільно"],
    salaryMin: 20000, salaryMax: 50000, currency: "UAH",
    perks: [], perksOther: ["служба за контрактом або мобілізацією"],
    employmentArrangement: "other",
    benefits: [
      "Можливість переведення чинних військовослужбовців за згодою командира",
      "Повна зайнятість",
      "Комунікаційна робота в підрозділі ЗСУ",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/7860579/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/7860579/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "work-8197542", title: "Відеооператор",
    companyId: null, companyName: "Служба підтримки ЦРУА",
    region: "Чернівецька область", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Знімати відеоматеріали та підтримувати візуальні комунікації підрозділу",
      "Працювати з монтажем, фотозйомкою та оперативною підготовкою матеріалів",
      "Дотримуватися дисципліни, дедлайнів і вимог безпеки",
    ],
    mustHave: [
      "Досвід відеозйомки або монтажу від 1 року",
      "Знання Adobe Premiere Pro або схожих інструментів",
      "Готовність до офіційної служби",
    ],
    niceToHave: ["Перевага надається ветеранам"],
    education: "Не вказано",
    skills: ["Відеозйомка", "Монтаж", "Фотозйомка", "Комунікації"],
    tools: ["Adobe Premiere Pro", "Adobe"],
    languages: ["Українська — вільно"],
    salaryMin: 30000, salaryMax: 50000, currency: "UAH",
    perks: [], perksOther: ["офіційна служба", "контракт або мобілізація"],
    employmentArrangement: "other",
    benefits: [
      "Офіційна служба: мобілізація до кінця воєнного стану або служба за контрактом",
      "Можливість переведення чинних військовослужбовців за згодою командира",
      "Відпустка та соціальні гарантії, описані в оригіналі",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Work.ua", sourceUrl: "https://www.work.ua/jobs/8197542/",
    sources: [{ name: "Work.ua", url: "https://www.work.ua/jobs/8197542/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "suspilne-69576", title: "Редактор, редакторка дня YouTube Суспільне Новини",
    companyId: "suspilne", region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Писати сценарії для відео, зокрема для формату YouTube Shorts",
      "Готувати відео до публікації: назви, описи та технічні завдання для обкладинок",
      "Редагувати інтерв'ю, репортажі та інші відеоматеріали",
      "Брати участь у щоденному плануванні контенту і наповненні YouTube-каналу",
    ],
    mustHave: [
      "Вища освіта за напрямом журналістики або суміжних спеціальностей",
      "Досвід роботи від 1 року на аналогічній посаді",
      "Досвід створення сценаріїв для YouTube-контенту",
      "Знання журналістських стандартів і розуміння принципів роботи YouTube",
    ],
    niceToHave: ["Досвід в інформаційно-аналітичних YouTube-проєктах"],
    education: "Вища освіта",
    skills: ["YouTube", "Сценарії", "Редагування", "Журналістські стандарти", "Відеоконтент"],
    tools: ["YouTube", "YouTube Shorts"],
    languages: ["Українська — вільно"],
    salaryMin: 31000, salaryMax: 31000, currency: "UAH",
    perks: [], perksOther: ["оклад до сплати податків", "можлива повністю дистанційна робота"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування",
      "Можливість працювати дистанційно або з офісу в центрі Києва",
      "Робота над розвитком YouTube-каналу Суспільне Новини",
    ],
    contactEmail: "", publishedAt: "2026-07-16", expiresAt: "2026-08-15",
    source: "Суспільне", sourceUrl: "https://corp.suspilne.media/nashi-vakansiyi/69576-redaktor-redaktorka-dnya-youtube-cuspilne-novyny/",
    sources: [{ name: "Суспільне", url: "https://corp.suspilne.media/nashi-vakansiyi/69576-redaktor-redaktorka-dnya-youtube-cuspilne-novyny/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "suspilne-69574", title: "Редактор, редакторка проєкту «Несеться» YouTube Суспільне Новини",
    companyId: "suspilne", region: "м. Київ", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Готувати матеріали для випусків: шукати, аналізувати та перевіряти інформацію",
      "Писати сценарії для епізодів і редагувати сценарії інших редакторів",
      "Працювати з джерелами, фактами, коментарями та експертними думками",
      "Брати участь у записах і зйомках, за потреби — працювати в кадрі",
    ],
    mustHave: [
      "Вища освіта",
      "Досвід роботи від 1 року в журналістиці, редактурі або створенні медіаконтенту",
      "Досвід написання сценаріїв і роботи з інформаційними джерелами",
      "Знання журналістських стандартів і принципів перевірки інформації",
    ],
    niceToHave: ["Досвід роботи з YouTube", "Англійська мова від B1"],
    education: "Вища освіта",
    skills: ["Редагування", "YouTube", "Сценарії", "Фактчекінг", "Медіаконтент"],
    tools: ["YouTube"],
    languages: ["Українська — вільно", "Англійська — буде перевагою"],
    salaryMin: 65000, salaryMax: 65000, currency: "UAH",
    perks: [], perksOther: ["оклад до сплати податків"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування",
      "Робота у професійній команді журналістів, редакторів і продюсерів",
      "Можливість створювати суспільно важливий YouTube-контент",
    ],
    contactEmail: "", publishedAt: "2026-07-16", expiresAt: "2026-08-15",
    source: "Суспільне", sourceUrl: "https://corp.suspilne.media/nashi-vakansiyi/69574-redaktor-redaktorka-proyektu-nesetsya-youtube-cuspilne-novyny/",
    sources: [{ name: "Суспільне", url: "https://corp.suspilne.media/nashi-vakansiyi/69574-redaktor-redaktorka-proyektu-nesetsya-youtube-cuspilne-novyny/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "suspilne-69555", title: "Редактор, редакторка соцмереж Українського радіо",
    companyId: "suspilne", region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Адаптувати матеріали радіопрограм для використання у соціальних мережах",
      "Створювати текстові та графічні матеріали для соцмереж",
      "Публікувати матеріали Українського радіо у Facebook та Instagram",
      "Моніторити тренди, формати й інструменти соціальних мереж",
    ],
    mustHave: [
      "Впевнене письмо українською мовою",
      "Розуміння редакційної роботи в соціальних мережах",
      "Уважність до стилістики, грамотності та коректності текстів",
      "Готовність працювати в гібридному форматі",
    ],
    niceToHave: ["Досвід роботи з медійними або радійними проєктами"],
    education: "Не вказано",
    skills: ["SMM", "Редагування", "Соцмережі", "Копірайтинг", "Радіоконтент"],
    tools: ["Facebook", "Instagram", "Meta"],
    languages: ["Українська — вільно"],
    salaryMin: 32000, salaryMax: 32000, currency: "UAH",
    perks: [], perksOther: ["оклад до сплати податків", "соціальні гарантії"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування та соціальні гарантії",
      "Графік понеділок-п'ятниця, 9:00-18:00",
      "Гібридний формат: поєднання офісної та дистанційної роботи",
    ],
    contactEmail: "", publishedAt: "2026-07-16", expiresAt: "2026-08-15",
    source: "Суспільне", sourceUrl: "https://corp.suspilne.media/bez-rubryky-uk/69555-redaktorka-sotsmerezh/",
    sources: [{ name: "Суспільне", url: "https://corp.suspilne.media/bez-rubryky-uk/69555-redaktorka-sotsmerezh/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "suspilne-69553", title: "Відеограф, відеографиня Українського радіо",
    companyId: "suspilne", region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Знімати відео та створювати динамічні візуальні матеріали",
      "Працювати з камерами, світлом та аудіообладнанням",
      "Монтувати відеоматеріали під технічні вимоги цифрових платформ",
      "Взаємодіяти з редакторами, ведучими та виробничою командою",
    ],
    mustHave: [
      "Досвід відеозйомки та монтажу",
      "Розуміння технічних вимог до цифрового відеоконтенту",
      "Уважність до якості відео- та аудіоматеріалів",
      "Дотримання редакційних стандартів і авторського права",
    ],
    niceToHave: ["Досвід роботи з медійними або радійними форматами"],
    education: "Не вказано",
    skills: ["Відеозйомка", "Відеомонтаж", "Диджитал", "Візуальний контент"],
    tools: ["Камера", "Світло", "Аудіообладнання", "Відеоредактори"],
    languages: ["Українська — вільно"],
    salaryMin: 32000, salaryMax: 32000, currency: "UAH",
    perks: [], perksOther: ["оклад до сплати податків", "соціальні гарантії"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування та соціальні гарантії",
      "Безпечне робоче середовище",
      "Участь у створенні відеоконтенту для Українського радіо",
    ],
    contactEmail: "", publishedAt: "2026-07-16", expiresAt: "2026-08-15",
    source: "Суспільне", sourceUrl: "https://corp.suspilne.media/nashi-vakansiyi/69553-videograf-ynya/",
    sources: [{ name: "Суспільне", url: "https://corp.suspilne.media/nashi-vakansiyi/69553-videograf-ynya/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "suspilne-69551", title: "Редактор, редакторка цифрового контенту Українського радіо",
    companyId: "suspilne", region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Створювати концепції контенту для соцмереж, зокрема коротких відео та графіки",
      "Затверджувати контент-план для соціальних мереж",
      "Ставити технічні завдання дизайнерам, монтажерам і SMM-фахівцям",
      "Координувати шлях цифрового контенту від ідеї до публікації",
    ],
    mustHave: [
      "Досвід роботи з цифровим контентом",
      "Розуміння соціальних мереж і коротких відеоформатів",
      "Навички планування, координації та постановки завдань",
      "Уміння аналізувати ефективність контенту",
    ],
    niceToHave: ["Досвід роботи з радійними або культурними медіапроєктами"],
    education: "Не вказано",
    skills: ["Диджитал-контент", "SMM", "Контент-план", "Редагування", "Координація"],
    tools: ["Facebook", "Instagram", "Meta"],
    languages: ["Українська — вільно"],
    salaryMin: 46500, salaryMax: 46500, currency: "UAH",
    perks: [], perksOther: ["оклад до сплати податків", "соціальні гарантії"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування та соціальні гарантії",
      "Безпечне робоче середовище",
      "Можливість впливати на розвиток цифрової аудиторії Українського радіо",
    ],
    contactEmail: "", publishedAt: "2026-07-16", expiresAt: "2026-08-15",
    source: "Суспільне", sourceUrl: "https://corp.suspilne.media/bez-rubryky-uk/69551-redaktor-ka-tsyfrovogo-kontentu/",
    sources: [{ name: "Суспільне", url: "https://corp.suspilne.media/bez-rubryky-uk/69551-redaktor-ka-tsyfrovogo-kontentu/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "suspilne-69549", title: "Режисер, режисерка монтажу для диджитал-платформ Суспільне Новини",
    companyId: "suspilne", region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Монтувати відео для YouTube, YouTube Shorts, Instagram та TikTok",
      "Оперативно готувати контент до публікації, у середньому 3-4 відео на день",
      "Працювати зі звуком, кольорокорекцією та адаптацією відео під різні платформи",
      "Дотримуватися дедлайнів і забезпечувати високу якість фінального матеріалу",
    ],
    mustHave: [
      "Досвід монтажу відеоконтенту для соціальних мереж від 1 року",
      "Вища освіта у журналістиці або суміжній сфері",
      "Знання Adobe Premiere Pro та Adobe After Effects",
      "Розуміння особливостей YouTube, Instagram і TikTok",
    ],
    niceToHave: ["Англійська мова буде перевагою"],
    education: "Вища освіта",
    skills: ["Відеомонтаж", "Диджитал", "YouTube", "Instagram", "TikTok"],
    tools: ["Adobe Premiere Pro", "Adobe After Effects", "YouTube", "TikTok"],
    languages: ["Українська — вільно", "Англійська — буде перевагою"],
    salaryMin: 31031, salaryMax: 31031, currency: "UAH",
    perks: [], perksOther: ["оклад до сплати податків"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування",
      "Гібридний формат роботи",
      "Робота з досвідченою командою над контентом для великих аудиторій",
    ],
    contactEmail: "", publishedAt: "2026-07-16", expiresAt: "2026-08-15",
    source: "Суспільне", sourceUrl: "https://corp.suspilne.media/nashi-vakansiyi/kyyiv/69549-rezhyser-rezhyserka-montazhu-dlya-didzhytal-platform-suspilne-novyny/",
    sources: [{ name: "Суспільне", url: "https://corp.suspilne.media/nashi-vakansiyi/kyyiv/69549-rezhyser-rezhyserka-montazhu-dlya-didzhytal-platform-suspilne-novyny/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "suspilne-66634", title: "Редактор, редакторка Суспільне Студія (YouTube)",
    companyId: "suspilne", region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Редагувати та оформлювати контент для YouTube-каналу «Суспільне Студія»",
      "Брати участь у підготовці спецетерів: теми, гості, структура етерів",
      "Аналізувати ефективність контенту та збирати аналітику платформи",
      "Формувати пропозиції щодо просування і розвитку проєкту на YouTube",
    ],
    mustHave: [
      "Вища освіта за напрямом журналістики або суміжних спеціальностей",
      "Досвід роботи від 1 року у медіа, digital або YouTube-проєктах",
      "Розуміння принципів роботи YouTube та цифрового контенту",
      "Навички роботи з аналітикою і контент-плануванням",
    ],
    niceToHave: ["Adobe Premiere Pro та Adobe Photoshop — буде перевагою"],
    education: "Вища освіта",
    skills: ["YouTube", "Редагування", "Аналітика", "Контент-планування", "Диджитал"],
    tools: ["YouTube", "Adobe Premiere Pro", "Adobe Photoshop"],
    languages: ["Українська — вільно"],
    salaryMin: 39000, salaryMax: 39000, currency: "UAH",
    perks: [], perksOther: ["оклад до сплати податків"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування",
      "Робота в команді одного з найбільших медіа України",
      "Професійний розвиток та участь у масштабних медійних проєктах",
    ],
    contactEmail: "", publishedAt: "2026-07-01", expiresAt: "2026-07-31",
    source: "Суспільне", sourceUrl: "https://corp.suspilne.media/nashi-vakansiyi/66634-redaktor-redaktorka-suspilne-studiya-youtube/",
    sources: [{ name: "Суспільне", url: "https://corp.suspilne.media/nashi-vakansiyi/66634-redaktor-redaktorka-suspilne-studiya-youtube/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-11282815", title: "Журналіст стрічки новин сайту",
    companyId: null, companyName: "ТРК «Київ» / Київ24",
    region: "м. Київ", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 2,
    responsibilities: [
      "Писати новини за першоджерелами, забезпечувати якість і точність матеріалів",
      "Моніторити ресурси міських та державних органів, соцмережі й медіа",
      "Створювати ексклюзивні новини на основі коментарів, включень та матеріалів телеканалу",
    ],
    mustHave: [
      "Вища освіта",
      "Досвід роботи у ЗМІ від 2 років",
      "Досконала українська мова",
      "Розуміння соціально-політичної ситуації в Києві, Україні та світі",
    ],
    niceToHave: ["Знання англійської мови"],
    education: "Вища освіта",
    skills: ["Журналістика", "Новини", "Першоджерела", "Редагування"],
    tools: ["CMS"],
    languages: ["Українська — вільно", "Англійська — буде перевагою"],
    salaryMin: 17000, salaryMax: 22000, currency: "UAH",
    perks: [], perksOther: ["безпечне робоче середовище"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування та соціальні гарантії",
      "Вечірня зміна 15:00-22:00",
      "Офіс поблизу метро «Лук'янівка»",
    ],
    contactEmail: "", publishedAt: "2026-07-24", expiresAt: "2026-08-23",
    source: "robota.ua", sourceUrl: "https://robota.ua/company2630388/vacancy11282815",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company2630388/vacancy11282815" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-11282772", title: "Редактор новин ранок",
    companyId: null, companyName: "ТРК «Київ»",
    region: "м. Київ", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 2,
    responsibilities: [
      "Готувати та редагувати новинні сюжети для ранкового ефіру",
      "Складати тексти новин і контролювати дотримання редакційної політики",
      "Організовувати роботу зі знімальною групою",
      "Працювати в ефірному режимі з дотриманням строків і вимог якості",
    ],
    mustHave: [
      "Досвід роботи від 2 років на аналогічній посаді",
      "Висока кваліфікація редактора",
      "Знання редакційної політики",
      "Вміння працювати в команді та відповідальність за результат",
    ],
    niceToHave: [],
    education: "Не вказано",
    skills: ["Редагування", "Телебачення", "Новини", "Ефір"],
    tools: ["CMS", "Ефірні системи"],
    languages: ["Українська — вільно"],
    salaryMin: 25000, salaryMax: 27000, currency: "UAH",
    perks: [], perksOther: ["корпоративне авто на ранкову зміну"],
    employmentArrangement: "labor",
    benefits: [
      "Офіційне працевлаштування",
      "Графік 05:00-11:00",
      "Офіс на Подолі",
    ],
    contactEmail: "", publishedAt: "2026-07-24", expiresAt: "2026-08-23",
    source: "robota.ua", sourceUrl: "https://robota.ua/company2630388/vacancy11282772",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company2630388/vacancy11282772" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-11227573", title: "Редактор стрічки новин",
    companyId: null, companyName: "Главком",
    region: "м. Київ", country: "Україна", format: "remote", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Оперативно шукати інформацію та ставити новини на сайт",
      "Відбирати головну інформацію, відокремлювати її від другорядної",
      "Писати зрозумілі новини та креативні заголовки",
    ],
    mustHave: [
      "Досвід роботи редактором стрічки новин",
      "Розуміння структури новини та редакційних стандартів",
      "Орієнтація у політиці та соціальних темах",
      "Грамотне й зрозуміле письмо",
    ],
    niceToHave: [],
    education: "Не вказано",
    skills: ["Новини", "Редагування", "Заголовки", "Політика", "Соціальні теми"],
    tools: ["CMS"],
    languages: ["Українська — вільно"],
    salaryMin: 22000, salaryMax: 27000, currency: "UAH",
    perks: [], perksOther: ["дистанційна робота"],
    employmentArrangement: "other",
    benefits: [
      "Повна зайнятість",
      "Робота дистанційна",
      "Редакційна робота в онлайн-виданні",
    ],
    contactEmail: "", publishedAt: "2026-07-18", expiresAt: "2026-08-17",
    source: "robota.ua", sourceUrl: "https://robota.ua/company13640526/vacancy11227573",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company13640526/vacancy11227573" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-11246935", title: "Редактор економічної стрічки новин",
    companyId: null, companyName: "Телерадіокомпанія Люкс, ПрАТ",
    region: "м. Київ", country: "Україна", format: "remote", remoteOk: true,
    employmentType: "full", experienceYears: 0,
    responsibilities: [
      "Моніторити економічні новини та інформаційний порядок денний",
      "Відбирати найважливіші теми для публікації",
      "Готувати та редагувати новинні матеріали",
      "Працювати з джерелами інформації та перевіряти факти",
    ],
    mustHave: [
      "Уважність до деталей",
      "Готовність навчатися та швидко адаптуватися",
      "Самостійність і відповідальність",
      "Інтерес до економіки, бізнесу та фінансових новин",
    ],
    niceToHave: ["Економічна освіта або досвід роботи з економічною тематикою"],
    education: "Не вказано",
    skills: ["Економічні новини", "Редагування", "Фактчекінг", "Новини"],
    tools: ["CMS"],
    languages: ["Українська — вільно"],
    salaryMin: 25000, salaryMax: 25000, currency: "UAH",
    perks: [], perksOther: ["оплачуваний випробувальний термін"],
    employmentArrangement: "other",
    benefits: [
      "Повна зайнятість",
      "Формат роботи може бути дистанційним, гібридним або офісним",
      "Графік понеділок-п'ятниця, 8-годинний робочий день",
    ],
    contactEmail: "", publishedAt: "2026-07-22", expiresAt: "2026-08-21",
    source: "robota.ua", sourceUrl: "https://robota.ua/company899888/vacancy11246935",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company899888/vacancy11246935" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-10958237", title: "Редактор стрічки новин (денна зміна)",
    companyId: null, companyName: "OBOZ.UA",
    region: "м. Київ", country: "Україна", format: "remote", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Рерайт і написання унікальних новинних текстів на різну тематику",
      "Оформлення новин в адмінці",
      "Опрацювання відеосюжетів",
      "Ведення текстових онлайн-трансляцій, Telegram і Facebook",
    ],
    mustHave: [
      "Досвід роботи в інтернет-медіа не менше року",
      "Розуміння інформприводу, ліду і бекграунду",
      "Орієнтація у політичній та міжнародній ситуації",
      "Грамотна українська і російська мови",
      "Розуміння основ SEO",
    ],
    niceToHave: [],
    education: "Не вказано",
    skills: ["Новини", "SEO", "Редагування", "Онлайн-трансляції", "Соцмережі"],
    tools: ["CMS", "Telegram", "Facebook"],
    languages: ["Українська — вільно", "Російська — вільно"],
    salaryMin: 18000, salaryMax: 18000, currency: "UAH",
    perks: [], perksOther: ["позмінна робота", "випробувальний термін"],
    employmentArrangement: "other",
    benefits: [
      "Віддалена робота",
      "Повна зайнятість",
      "Плаваючі вихідні",
    ],
    contactEmail: "", publishedAt: "2026-07-10", expiresAt: "2026-08-09",
    source: "robota.ua", sourceUrl: "https://robota.ua/company972302/vacancy10958237",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company972302/vacancy10958237" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-9419117", title: "Редактор стрічки новин",
    companyId: null, companyName: "УРА-Информ",
    region: "м. Київ", country: "Україна", format: "remote", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Швидко знаходити інформаційні приводи та перевіряти факти",
      "Писати й редагувати новини для інформаційних сайтів",
      "Працювати з SEO-заголовками, пошуковою видачею та Google Discover",
      "Використовувати AI-інструменти для пришвидшення пошуку й структурування текстів",
    ],
    mustHave: [
      "Досвід у новинах, SEO та роботі з великим обсягом інформації",
      "Грамотна українська та російська мови",
      "Розуміння Google, SEO-заголовків і Google Discover",
      "Уважність, відповідальність і оперативність",
    ],
    niceToHave: ["SEO-кейси або матеріали, що давали хороший трафік"],
    education: "Не вказано",
    skills: ["Новини", "SEO", "Google Discover", "Фактчекінг", "AI-інструменти"],
    tools: ["ChatGPT", "Google Discover", "CMS"],
    languages: ["Українська — вільно", "Російська — вільно"],
    salaryMin: 7700, salaryMax: 29000, currency: "UAH",
    perks: [], perksOther: ["бонуси після випробувального терміну", "гнучкий графік"],
    employmentArrangement: "other",
    benefits: [
      "Віддалена робота",
      "Гнучкий графік",
      "Можливість збільшення доходу залежно від результатів",
    ],
    contactEmail: "", publishedAt: "2026-07-01", expiresAt: "2026-07-31",
    source: "robota.ua", sourceUrl: "https://robota.ua/company817008/vacancy9419117",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company817008/vacancy9419117" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-10387142", title: "Редактор соціальних мереж",
    companyId: null, companyName: "Zmist",
    region: "м. Київ", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Писати тексти для ресурсів проєкту",
      "Аналізувати та моніторити інформаційний простір",
      "Взаємодіяти з аудиторією ресурсів",
      "Створювати технічні завдання для креативних матеріалів",
      "Генерувати ідеї для розвитку проєкту та брати участь в їх реалізації",
    ],
    mustHave: [
      "Досвід створення якісного контенту для різних каналів комунікації",
      "Грамотна українська мова",
      "Ініціативність і проактивність",
      "Готовність працювати з офісу",
    ],
    niceToHave: ["Досвід у медіа-агенції або комунікаційних кампаніях"],
    education: "Не вказано",
    skills: ["Соцмережі", "Копірайтинг", "Редагування", "Моніторинг", "Комунікації"],
    tools: ["Соцмережі", "Canva"],
    languages: ["Українська — вільно"],
    salaryMin: 25000, salaryMax: 25000, currency: "UAH",
    perks: [], perksOther: ["бонуси", "офіс у центрі", "регулярний перегляд зарплати"],
    employmentArrangement: "other",
    benefits: [
      "Робота з офісу з понеділка по п'ятницю",
      "8-годинний робочий день з 9:00",
      "Можливість працювати з різноманітною інформацією і проявити творчість",
    ],
    contactEmail: "", publishedAt: "2026-07-12", expiresAt: "2026-08-11",
    source: "robota.ua", sourceUrl: "https://robota.ua/company14645443/vacancy10387142",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company14645443/vacancy10387142" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-11179755", title: "Журналіст стажер",
    companyId: null, companyName: "Rikinson",
    region: "Вся Україна", country: "Україна", format: "remote", remoteOk: true,
    employmentType: "project", experienceYears: 0,
    responsibilities: [
      "Щотижня готувати тему і сценарій нового випуску",
      "Писати підписи, заголовки, описи та CTA для Instagram і Telegram",
      "Проводити вуличні інтерв'ю у місті проживання",
      "Відстежувати формати Instagram, Reels і TikTok та аналізувати результати випусків",
    ],
    mustHave: [
      "Високий рівень української мови і природне мовлення в кадрі",
      "Власні соцмережі з контентом",
      "Профільна освіта або навчання: журналістика, філологія, комунікації, PR, медіа чи реклама",
      "Комунікативність і готовність працювати з незнайомими людьми",
    ],
    niceToHave: ["Досвід публічних виступів, подкастів або ведення заходів"],
    education: "Профільна освіта або навчання буде перевагою",
    skills: ["Інтерв'ю", "Сценарії", "Short video", "Соцмережі", "Робота в кадрі"],
    tools: ["Instagram", "TikTok", "YouTube", "Telegram"],
    languages: ["Українська — вільно"],
    salaryMin: 12000, salaryMax: 18000, currency: "UAH",
    perks: [], perksOther: ["бонуси за KPI", "технічне забезпечення зйомок"],
    employmentArrangement: "civil",
    benefits: [
      "Віддалена сценарна робота у зручному графіку",
      "Оператор та обладнання надаються компанією",
      "Усі випуски виходять на офіційних каналах Rikinson із зазначенням авторства",
    ],
    contactEmail: "", publishedAt: "2026-07-07", expiresAt: "2026-08-06",
    source: "robota.ua", sourceUrl: "https://robota.ua/company16165461/vacancy11179755",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company16165461/vacancy11179755" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-11277523", title: "Прес-секретар",
    companyId: null, companyName: "ГО «Діалог, права, обов'язки»",
    region: "м. Київ", country: "Україна", format: "hybrid", remoteOk: true,
    employmentType: "full", experienceYears: 3,
    responsibilities: [
      "Готувати пресрелізи, офіційні заяви, коментарі та новини",
      "Комунікувати з журналістами та редакціями ЗМІ",
      "Організовувати пресконференції, брифінги, інтерв'ю та публічні заходи",
      "Вести медіабазу, моніторити згадки й координувати інформаційні проєкти",
    ],
    mustHave: [
      "Досвід роботи прес-секретарем, PR-менеджером або журналістом від 3 років",
      "Досвід підготовки пресрелізів, коментарів та організації пресзаходів",
      "Відмінна українська мова",
      "Англійська — від B2",
      "Високий рівень комунікаційних навичок і стресостійкість",
    ],
    niceToHave: ["Власна база контактів зі ЗМІ"],
    education: "Не вказано",
    skills: ["PR", "Медіарилейшнз", "Пресрелізи", "Публічні заходи", "Моніторинг"],
    tools: ["Медіабаза", "Соцмережі"],
    languages: ["Українська — вільно", "Англійська — від B2"],
    salaryMin: 45000, salaryMax: 65000, currency: "UAH",
    perks: [], perksOther: ["можливість працювати віддалено"],
    employmentArrangement: "other",
    benefits: [
      "Гібридний або офісний формат",
      "Можливість професійного розвитку",
      "Розвиток медійного напряму громадської організації",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "robota.ua", sourceUrl: "https://robota.ua/company16682398/vacancy11277523",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company16682398/vacancy11277523" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-11240614", title: "SMM-менеджер віддалено",
    companyId: null, companyName: "Board, міжнародна бізнес-спільнота",
    region: "м. Київ", country: "Україна", format: "remote", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Вести кілька сторінок і проєктів BOARD",
      "Створювати контент-плани, тексти, сторіс, Reels та сценарії",
      "Самостійно створювати контент у Canva, CapCut або інших інструментах",
      "Аналізувати аудиторію, конкурентів і використовувати AI для контенту",
    ],
    mustHave: [
      "Досвід роботи в SMM від 1 року",
      "Розуміння сучасних соціальних мереж і контент-маркетингу",
      "Портфоліо",
      "Володіння Canva, CapCut або аналогічними інструментами",
      "Грамотна українська мова",
    ],
    niceToHave: ["Досвід роботи з ChatGPT, Claude, Gemini або іншими AI-інструментами"],
    education: "Не вказано",
    skills: ["SMM", "Контент-маркетинг", "Reels", "AI-контент", "Аналітика"],
    tools: ["Canva", "CapCut", "ChatGPT", "Claude", "Gemini"],
    languages: ["Українська — вільно"],
    salaryMin: 25000, salaryMax: 30000, currency: "UAH",
    perks: [], perksOther: ["24 робочі дні оплачуваної відпустки"],
    employmentArrangement: "other",
    benefits: [
      "Віддалений формат роботи",
      "Доступ до внутрішніх навчань, менторів та бізнес-подій",
      "Можливість перегляду доходу за результатами роботи",
    ],
    contactEmail: "", publishedAt: "2026-07-24", expiresAt: "2026-08-23",
    source: "robota.ua", sourceUrl: "https://robota.ua/company11417589/vacancy11240614",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company11417589/vacancy11240614" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "robota-11265895", title: "SMM-менеджер (Instagram, TikTok)",
    companyId: null, companyName: "StudentUA",
    region: "м. Київ", country: "Україна", format: "remote", remoteOk: true,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Планувати стратегії розвитку акаунтів і росту охоплень",
      "Створювати контент-плани з викладачами для Instagram та TikTok",
      "Генерувати ідеї та сценарії для контенту, моніторити тренди",
      "Готувати технічні завдання викладачам, монтажеру та дизайнеру",
      "Аналізувати метрики: охоплення, підписники, ERR і кількість лідів",
    ],
    mustHave: [
      "Досвід у SMM",
      "Системність і креативність",
      "Розуміння Instagram та TikTok",
      "Вміння працювати з контентними воронками",
    ],
    niceToHave: ["Досвід роботи з освітніми продуктами"],
    education: "Не вказано",
    skills: ["SMM", "Instagram", "TikTok", "Контент-воронки", "Аналітика"],
    tools: ["Instagram", "TikTok", "Canva", "CapCut"],
    languages: ["Українська — вільно"],
    salaryMin: 25000, salaryMax: 30000, currency: "UAH",
    perks: [], perksOther: ["гнучкий графік"],
    employmentArrangement: "other",
    benefits: [
      "Віддалена робота",
      "Можливість стати тімлідером або керівником напряму SMM",
      "Робота з акаунтами з активною аудиторією",
    ],
    contactEmail: "", publishedAt: "2026-07-09", expiresAt: "2026-08-08",
    source: "robota.ua", sourceUrl: "https://robota.ua/company10359326/vacancy11265895",
    sources: [{ name: "robota.ua", url: "https://robota.ua/company10359326/vacancy11265895" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "lobbyx-smm-csoa", title: "SMM-спеціаліст",
    companyId: null, companyName: "Центр спеціальних операцій «А» СБУ",
    region: "м. Київ", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Створювати контент для Instagram, TikTok, YouTube, Facebook і X",
      "Писати пости, новини, оперативні повідомлення, аналітичні пояснення, заголовки та описи",
      "Готувати SMM-стратегію, контент-план і SMM-кампанії",
      "Моніторити соцмережі, згадки, тональність, тренди та інформаційні приводи",
    ],
    mustHave: [
      "Досвід комунікаційної роботи та SMM від 1 року",
      "Уміння створювати контент для різних платформ",
      "Знання алгоритмів соцмереж, трендів і механік залучення",
      "Навички фактчеку, аналізу джерел і медіамоніторингу",
    ],
    niceToHave: ["Досвід у громадському секторі, медіа, бізнесі або аналітиці"],
    education: "Не вказано",
    skills: ["SMM", "Фактчекінг", "Контент", "Кризові комунікації", "Meta Ads"],
    tools: ["Canva", "Figma", "Adobe Photoshop", "Adobe Premiere Pro", "Meta Ads Manager"],
    languages: ["Українська — вільно"],
    salaryMin: 43000, salaryMax: 45000, currency: "UAH",
    perks: [], perksOther: ["служба за контрактом або мобілізацією", "спорядження і ресурси"],
    employmentArrangement: "other",
    benefits: [
      "Мобілізація до кінця воєнного стану або служба за контрактом",
      "Можливість переведення чинних військовослужбовців за згодою командира",
      "ППД — місто Київ, регулярні навчання та професійний розвиток",
    ],
    contactEmail: "", publishedAt: "2026-06-29", expiresAt: "2026-08-28",
    source: "Lobby X", sourceUrl: "https://lobbyx.army/tor/smm-spetsialist-do-tsentr-spetsialnykh-operatsiy-a/",
    sources: [{ name: "Lobby X", url: "https://lobbyx.army/tor/smm-spetsialist-do-tsentr-spetsialnykh-operatsiy-a/" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
  {
    id: "dcz-04502602040011", title: "Журналіст",
    companyId: null, companyName: "КП «Дніпровська міська студія телебачення» ДМР",
    region: "Дніпропетровська область", country: "Україна", format: "office", remoteOk: false,
    employmentType: "full", experienceYears: 1,
    responsibilities: [
      "Готувати оперативні, публіцистичні, документальні та телевізійні матеріали",
      "Виїжджати на місця подій для висвітлення подій в країні",
      "Виступати з власними матеріалами",
      "Брати участь у телепрограмах і трансляціях",
    ],
    mustHave: [
      "Досвід або готовність працювати у телевізійній журналістиці",
      "Вміння готувати матеріали для ефіру",
      "Оперативність і відповідальність",
      "Готовність працювати в офісному форматі в Дніпрі",
    ],
    niceToHave: ["Досвід роботи редактором або кореспондентом"],
    education: "Не вказано",
    skills: ["Журналістика", "Телебачення", "Репортаж", "Редагування", "Ефір"],
    tools: ["Телевізійне обладнання", "CMS"],
    languages: ["Українська — вільно"],
    salaryMin: 12000, salaryMax: 12000, currency: "UAH",
    perks: [], perksOther: ["постійна робота", "5-денний робочий тиждень"],
    employmentArrangement: "labor",
    benefits: [
      "Вакансія зареєстрована через Державну службу зайнятості",
      "Повна зайнятість",
      "Телевізійна редакційна робота в Дніпрі",
    ],
    contactEmail: "", publishedAt: "2026-07-28", expiresAt: "2026-08-27",
    source: "Державна служба зайнятості", sourceUrl: "https://www.dcz.gov.ua/job/single/04502602040011",
    sources: [{ name: "Державна служба зайнятості", url: "https://www.dcz.gov.ua/job/single/04502602040011" }],
    foundBy: "promedia", direct: false, moderationStatus: "approved", active: true,
  },
];
